name: Build and Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn verify
    - name: Coverage
      run: mvn -DrepoToken="${{ secrets.COVERALLS_REPO_TOKEN }}" coveralls:report
